### ISSUE TITLE
remove logging

### ISSUE THREAD

**Issue by gravityblast** [status-im/status-keycard-java#5]
For security reasons it would be better if we can remove logging or at least have it as an option.
For example `Log.d(TAG, String.format("RESPONSE %s %n-----------------------", Hex.toHexString(resp)));`, maybe it can leak some information.

**Comment by ligi** [comment]
timber is nice for this: https://github.com/JakeWharton/timber

**Comment by bitgamma** [comment]
APDU logging is done with Log.d, so is only visible on debug builds, no? It could be beneficial to use timber, but at the same time I wouldn't want to add dependencies unless strictly necessary.

However, the SecureChannel is designed to resist any kind of passive MITM, so logging the encrypted C-APDU and R-APDU cannot leak anything sensitive.

And then again, since almost all APDUs are fully encrypted, logging them does not give very much, so it could be removed altogether (or I could limit to logging header fields). What do you think?

**Comment by gravityblast** [comment]
Yeah maybe it's not a problem. I opened the issue after I saw the logs just not to forget, but maybe it's not a problem. As long as there aren't other kind of logs around

**Comment by ligi** [comment]
> APDU logging is done with Log.d, so is only visible on debug builds, no?

no - this is only the log level - there is no automatic filtering for debug 

timber is a small dependency
anyway I would also not put it high on the list of things to do if it is no real attack vector

**Comment by bitgamma** [comment]
I am going to switch logging to header only. The data is encrypted anyway, so showing it makes no sense and the log becomes more readable

**Comment by gravityblast** [comment]
👍
